name: laminage
channels:
 - conda-forge
dependencies:
 - python=3.7*
 - pip=20
 - dask
 - dask-jobqueue
 - fsspec
 - gcsfs
 - geopandas
 - holoviews
 - hvplot
 - ipywidgets
 - ipyleaflet
 - jupyter-panel-proxy
 - line_profiler
 - matplotlib-base
 - numpy
 - pandas
 - panel
 - scipy
 - pip :
    -  dbfread


