name: laminage
channels:
 - conda-forge
dependencies:
 - python=3.8*
 - pip=20
 - appmode
 - bottleneck
 - dask
 - dask-jobqueue
 - fsspec
 - gcsfs
 - s3fs
 - geopandas
 - holoviews
 - hvplot
 - ipywidgets
 - ipyleaflet
 - jupyter-panel-proxy
 - line_profiler
 - send2trash
 - matplotlib-base
 - netcdf4
 - numpy
 - pandas
 - panel
 - tiledb-py
 - scipy
 - xarray
 - zarr
 netCDF4 bottleneck
 - pip :
   - git+https://github.com/hydrologie/pydsstools.git
   - spotpy

