name: laminage
channels:
 - conda-forge
dependencies:
 - python=3.8*
 - pip=20
 - appmode
 - dask
 - dask-jobqueue
 - fsspec
 - gcsfs
 - s3fs
 - geopandas
 - holoviews
 - hvplot
 - ipywidgets
 - ipyleaflet
 - jupyter-panel-proxy
 - line_profiler
 - send2trash
 - matplotlib-base
 - numpy
 - pandas
 - panel
 - tiledb-py
 - scipy
 - xarray
 - zarr
 - pip :
   - https://github.com/gyanz/pydsstools/blob/master/dist/pydsstools-2.0-cp38-cp38-linux_x86_64.whl
   - spotpy

